version : '3'

services:
  backend:
    restart: always
    build: ./backend
    links:
      - mongo
  frontend:
   build: ./frontend/
   links:
      - backend
   ports:
    - 4000:4000
    - 3000:3000
     

   
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  
   