version : '3'

services:
  
  frontend:
   build: ./frontend/
   environment:
    - BACKEND_URL=backend
   links:
      - backend
   ports:
    - 80:80
    - 3000:3000

  backend:
    restart: always
    build: ./backend
    links:
      - mongo
    ports: 
      - 4000:4000
     

   
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  
   